### ISSUE TITLE
Custom Templates are not loading, backdrop is retained and app locks out

### ISSUE THREAD

**Issue by kshaaban-** [guylabs/ion-autocomplete#112]
I was trying to create a different template for the search modal, but it didn't seem to be working at all for me. So I copied the default template into its own html file and tried to run it using `template-url` but the app just retains the backdrop, and the template doesn't load up.

The issue can be seen [in this plnkr](http://plnkr.co/edit/a1f4m9KCmPMhiM7QZJjU?p=preview)

**Comment by guylabs** [comment]
Hi Khaled,

in your template you use this this as the first line:

```html
<div class="ion-autocomplete-container ' + ionAutocompleteController.randomCssClass + ' modal" style="display: none;">
```

But there the problem is the `randomCssClass` which need to be set correctly. So when you add this as the first line the example works properly:

```html
<div class="ion-autocomplete-container {{viewModel.randomCssClass}} modal" style="display: none;">
```

You can read more here how to set it properly: https://github.com/guylabs/ion-autocomplete#template-url

Thanks and regards,

Guy

**Comment by kshaaban-** [comment]
Whoa! :worried: idk how I missed that.. :+1: Thank you!
