### ISSUE TITLE
ng-disabled is working

### ISSUE THREAD

**Issue by keremtiryaki** [guylabs/ion-autocomplete#117]
i need to disable the autocompleter but ng-disabled is not working.

is there any other way to disable the autocompleter?

**Comment by guylabs** [comment]
Hi Kerem,

what exactly is not working when you disable the `input` field? It still pops up when the user clicks on it? If that is the case please set the `manage-externally` to true, as then you are not able to click  on it anymore. See https://github.com/guylabs/ion-autocomplete#manage-externally for more details.

If that did not help, can you please elaborate more on this issue with a codepen such that I can right away have a look at it?

Thanks and regards,

Guy

**Comment by keremtiryaki** [comment]
Hey Guy,

I am sorry about my question. Because i found an another bug in my app.
I checked it again: http://codepen.io/anon/pen/meNddo?editors=101
ion-autocomplete is working very well with ng-disabled option :+1: 
please ignore my question 

Thanks

**Comment by guylabs** [comment]
Hi Karem,

ok nice that it worked. So I will close the issue.

Thanks and regards,

Guy

**Comment by allanevargas** [comment]
Hi @guylabs,

I'm currently experiencing the same issue but I have figured out why. I am currently using the plugin on my AngularJS/Ionic Type 1 application.

When doing my development I use `ionic serve --lab` or `ionic serve` to debug, etc. When running `ionic serve`, it runs on the browser but I use the device toolbar under Chrome DevTools to simulate mobile devices. I found that when doing this, even though I have `ng-disabled="true"` or `<input disabled>` it still triggers the autocomplete. However, if I remove the mobile simulation and just run it as is on the browser it does not trigger it as it should since the field is disabled.

I have also tried this with `ionic serve --lab` which also opens/runs on the browser but the application is in it's contained emulator, rather than me forcing it to simulate to a mobile device via Chrome DevTools. In this environment it works as it should and does not open the autocomplete modal. 

Finally, I also tried this on my mobile device (Android, S9+) and it doesn't work. It still opens the autocomplete even though the field is disabled. Strange. I was wondering what I was doing wrong when I was inspecting @keremtiryaki's codepen as his browser version is working as it should but mine isn't and there wasn't a lot of differences in code.

As you've linked there, it seems that I can fix it by using `manage-externally` but is there any way around this where `ng-disabled` works in all environments?

Thanks

Allan

**Comment by guylabs** [comment]
Hi @aecvargas 

Thanks for the detailed explanations of your issue. I did not work on the autocomplete for a long time now and it looks like there are several new major versions of Ionic and I guess it would be best to check if this also happens on those versions first.

Currently I just know of the `manage-externally` option to fix this issue. Any other issues with the different browser/dev tools setup I am not familiar with and could as well happen with a default input field from Ionic. (Did you try that once?)

I hope I could help you with that answer.

Thanks and regards

Guy
