### ISSUE TITLE
Ionic app crash on IOS 9 after opening and closing multiple times autocomplete view

### ISSUE THREAD

**Issue by eleva** [guylabs/ion-autocomplete#123]
Hi,
we use ion-autocomplete in a Ionic app (ionic version is 1.1.1).
During our test on ios 9.1 (Iphone 5s), our app crashes if we click on field and then we go back with back button, repeating this pattern multiple times, without doing anything else. 
It seems that after three/four times the autocomplete view enters, the app crashes.
We load autocomplete data with a query on local data, stored in local storage: our callbackMethod is just a check on an array to find out if name cointains the digit.

We can reproduce the bug also testing the app on Iphone 4s (IOS 9.1).

We use wkWebView, adding this plugin to cordova https://github.com/Telerik-Verified-Plugins/WKWebView

We use latest version of cordova platform related to Ionic CLI (3.9.2 for ios platform)

We can't figure out what's going on: it seems related to autocomplete view entering (our app crashes only in this scenario).
Do you have any suggestions?

Thank you,
Eleva Dev Team

**Comment by guylabs** [comment]
Hi,

which version of the `ion-autocomplete` do you use? Ionic version `1.1.1` is only supported on the master currently so please try it with the master instead of `0.3.1`. I never tested it with the `wkWebView` so I just use the standard web views of the system itself.

I would create an example where you change the source of the `ion-autocomplete.js` in the `ionAutocompleteController.showModal()` method. There the whole logic is implemented how to show the modal, hide it, register the back button etc. Maybe I would remove as much as possible and then check what is causing the issue. It is hard to test here as I just use Android.

Maybe also try to create a small app which just has a button which then shows a modal and registers the back button and see if the issue also happens there. If this is the case then this would be an Ionic issue and has nothing to do with the `ion-autocomplete`.

I hope I could help you in some way.

Happy christmas and regards,

Guy

**Comment by guylabs** [comment]
Hi,

due to inactivity I will close the issue. If you still have any issues or remarks please add a comment or reopen the issue.

Thanks and regards,

Guy
