### ISSUE TITLE
input value with multiselect

### ISSUE THREAD

**Issue by amilino** [guylabs/ion-autocomplete#170]
Hi,

I am using multiselect in a way of selecting couple of items from the list and displaying selected items bellow autocomplete component (after clicking Done button) , together with some other information connected to selected item. If you are using component with having maximum number of selected items equals one, everything is ok. But if you have multiselect and if you select a lot of items, then you will see only couple of selected items fitted to the screen. How can I disable displaying of all selected item and have placeholder value displayed all the time... Because from the user point of view there is no need to display all selected item if selected items list is too long.

Thank you in advance.

Regards,
Alan

**Comment by guylabs** [comment]
Hi Alan,

this issue relates to the #169 as there the discussion is ongoing about the tags support.

I think it is valuable information for the user that he sees what is selected in the input field such that he does not need to click on the input again to see the selected items.

I know that this is something which does not look nice, but as a work around you could also use a text area instead of an input field, as there you will see all selected options. Would that be a valuable workaround for you?

If not then please join the conversation about the tags or maybe create a PR/branch with a prototype with the tags as I think this would be the way to go for this use case.

Thanks and regards,

Guy

**Comment by amilino** [comment]
I am displaying selected items in div element below my autocomplete control. Together with manage-externally="true" and also applied style="display:none;" on input element. That's my workaround, thank you for your answer anyway.

Regards,
Alan
