### ISSUE TITLE
Not Working if the autocomplete is not on the main page

### ISSUE THREAD

**Issue by enyosolutions** [guylabs/ion-autocomplete#191]
Hello,

I can't get the autocomplete to work. I have a settings page, with the ion-autocomplete.

If refresh the page in ionic serve, being already on the page it works.
However if i initialize the app on the home page and navigate to the settings it doesn't. The clicks are not registered on the element, and i can't find the events in the chrome inspector

Any idea where is the issue ?

Providing a pen is a bit hard since it involves creating two templates...

**Comment by guylabs** [comment]
Hi @enyosolutions,

sorry for my delay but I was on a longer trip and now I am working partially.

can you maybe provide the `ion-autocomplete` directive configuration? Have you also added a custom template? Do you add the directive inside another modal or any other kind of container instead of a standard Ionic container?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi

could you maybe answer the questions. If not I will close the issue and you can reopen it whenever you have time again.

Thanks and regards,

Guy
