### ISSUE TITLE
Move template from array to file

### ISSUE THREAD

**Issue by RamprakashJ** [guylabs/ion-autocomplete#2]
To write custom template it ll be easy if it is in separate file and include it using templateUrl

**Comment by guylabs** [comment]
Hi,

I will check that and add it to the next release. I hope I'm able to do this this week.

Thanks for the idea and regards,

Guy

**Comment by guylabs** [comment]
I've added the ability to specify a `template-url` attribute on the directive to be able to pass in an external template. You can read more here: https://github.com/guylabs/ion-autocomplete#template-url. Can you please test it on the master and tell me if it works for you because I want to release 0.2.0 this Sunday.

Thanks and regards,

Guy
