### ISSUE TITLE
Remove items selected from item list or other way to separate items from "select" and "selected" list

### ISSUE THREAD

**Issue by ziobudda** [guylabs/ion-autocomplete#201]
Is there a possibility to remove the item included in the select items list ? I have 50+ items and when my user scroll he can not see that the item, that he has clicked, has been chosen/inserted in the selected list.  

Or a way to have only one list with the recycle icon near the element chosen. 

Thanks and sorry for my bad english.

**Comment by guylabs** [comment]
Hi @ziobudda 

can you maybe elaborate more on that as I cannot really understand what the issue is. You mean you have 50+ items (from the back end) which are displayed right? And what about the recycle icon?

Can you maybe show me the configuration of the directive or create a codepen with an example of how you configured it?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @ziobudda 

could you maybe answer my questions above? I will close the issue now due to inactivity. If you have any comments please add them here and we can reopen it.

Thanks and regards,

Guy
