### ISSUE TITLE
Setting ng-model doesn't work

### ISSUE THREAD

**Issue by jvaclavik** [guylabs/ion-autocomplete#24]
Hello,
I'd like to use 2 autocompletes and the second one depends on the first one. If first change its value I need to delete or set up specific value of ng-model on second autocomplete. I didn't find how can I do it.
If I just simply change ng-model variable, it doesn't have effect on autocomplete. It still shows me old value.
Is it possible to fix it somehow?

Thanks!
Jan

**Comment by guylabs** [comment]
Hi Jan,

can you maybe provide an example ? (you can take the https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.single-select.e2e.html as template file) Because if you have the same model on both autocomplete components then you are just able to modify the same model and I don't see the added value if you have this? What do you exactly mean with "depends on the first one" ? 

Thanks and regards,

Guy

**Comment by jvaclavik** [comment]
Hello Guy,
I tried your example and it was exactly what I needed, but I didn't find it before in docs. There was mistake, because when I wanted to delete value I replaced model variable for {} instead of "".
Thanks for your help!

Best regards,
Jan

**Comment by guylabs** [comment]
Hi Jan,

ok nice that I could help.

Thanks and regards,

Guy

**Comment by micheladrion** [comment]
Hell. guylabs.

I can not get model value from autocomplete input when item is been selected.

Model value has never been changed.

How can I get model value of input.

Thank You, Michel.

**Comment by guylabs** [comment]
Hi Michel,

can you maybe have a look at this test html: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.single-select.e2e.html and adapt your code to this one? Or can you show me your code with the ion-autocomplete configuration and the method which returns the items. (maybe also a sample of the data)

Thanks and regards,

Guy
