### ISSUE TITLE
Suggestion list won't show for the first time you start typing 

### ISSUE THREAD

**Issue by jaschahal** [guylabs/ion-autocomplete#26]
Hi 

This is weird and probably I must be missing something, but if you can have a look that would be nice

Here is a codepen I did
http://codepen.io/jaschahal/pen/OVppRb

How to reproduce

1. Open above link in any browser
2. Click on the text field to open autocomplete modal
3. Start typing "Item" ---> No suggestions show up.
4. Delete text from input box and start typing again... --> it works perfectly now

Please let me know if I am missing something

Thanks in advance

Jas

**Comment by jaschahal** [comment]
Ok seek like something to do with 

<ion-item collection-repeat
vs
<ion-item ng-repeat

so, ng-repeat works vs collection-repeat don't

weird... checking now whats going on...

btw I am using ionic 1.0.0

jas

**Comment by guylabs** [comment]
Hi Jas,

I just had a look and I could reproduce it. Can you maybe try to reproduce it with the following test html file: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.single-select.e2e.html ? Because this is an e2e test html and the protractor tests are running through. I'm just guessing but could it be a codepen/browser issue? I shortly tested with safari and there the layout is broken but the items are fetched on the first type of a letter.

Thanks and regards,

Guy

**Comment by jaschahal** [comment]
Yeah right, that's working, thanks for that link. Now I have to drill down to see why other stuff didn't work. 

Thanks heaps for your help mate.

Much appreciated.

Jas

**Comment by guylabs** [comment]
Well you do not need to set the `items-method-value-key`. When it's empty you can pass in an array as you did in your example. You just need to set the proper `item-view-value-key` to set which property to display in the list.

Good that you could fix the issue. I didn't notice the mistake immediately.

Thanks and regards,

Guy

**Comment by jaschahal** [comment]
Hi Guy,

Yeah true. I realized this mistake. Thanks again.

I've modified my codepen example, just in case anyone else is stuck when getting started with autocomplete module, like the way I did.

Thanks again for your help.

Cheers,

Jas
