### ISSUE TITLE
Done button dosnt show

### ISSUE THREAD

**Issue by benag** [guylabs/ion-autocomplete#65]
Done button doesnt show in ionic

**Comment by guylabs** [comment]
Hi,

this is not that much information such that I could have a look at it ;). Could you maybe provide the code how you configure the component and what kind of `ion-autocomplete` and Ionic version you are using? It may be related to #64 because the Ionic version doesn't match.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi,

are there any news on this? You can always reopen the issue if there is something more.

Thanks and regards,

Guy
